### ISSUE TITLE
Revert PHP used with Prestashop 8 to PHP 8.1

### ISSUE THREAD

**Issue by kathep** [YunoHost-Apps/prestashop_ynh#39] opened 2023-10-29 22:37 UTC
### Describe the bug

Prestashop 8.1.1 and 8.1.2 are only compatible with PHP 8.1. But currently the Prestashop package ships with PHP 8.2.

### Context

Prestashop on Yunohost is throwing PHP errors because of this, including on import of categories.

### Expected behavior

Please change PHP version in Sury to 8.1 for the Prestashop package.

### Logs

Unknown error on line 2578 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$actions is deprecated

Unknown error on line 2579 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$simple_header is deprecated

Unknown error on line 2580 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$bulk_actions is deprecated

Unknown error on line 2589 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$orderBy is deprecated

Unknown error on line 2590 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$orderWay is deprecated

Unknown error on line 2591 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$listTotal is deprecated

Unknown error on line 2595 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$shopLinkType is deprecated

Unknown error on line 2599 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$languages is deprecated

Unknown error on line 2600 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$specificConfirmDelete is deprecated

Unknown error on line 2601 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$imageType is deprecated

Unknown error on line 2602 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$no_link is deprecated

Unknown error on line 2603 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$colorOnBackground is deprecated

Unknown error on line 2604 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$ajax_params is deprecated

Unknown error on line 2606 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$default_form_language is deprecated

Unknown error on line 2613 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$row_hover is deprecated

Unknown error on line 2614 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$position_identifier is deprecated

Unknown error on line 2620 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$list_id is deprecated

Unknown error on line 2624 in file /var/www/prestashop/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$list_skip_actions is deprecated

**Comment by kathep** [comment] 2023-11-02 22:32
These issues arise when trying to access Categories that have been added via the bulk import feature. But I believe they are due to PHP version conflicts. I'd be grateful if someone can help/take a look.

**Comment by kathep** [comment] 2023-11-09 06:35
Bump bump. Can anyone help with this?

**Comment by ericgaspar** [comment] 2023-11-10 08:00
#40 brings back PHP8.1. Can you try to upgrade from testing

**Comment by alexAubin** [comment] 2023-12-19 15:53
Closing, assuming the issue is fixed

**Closed by alexAubin** 2023-12-19 15:53 UTC
